CREATE SCHEMA `petshop` DEFAULT CHARACTER SET utf8;

USE petshop;

CREATE TABLE petshop (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    especie VARCHAR(55) NOT NULL,
    raca VARCHAR(55) NOT NULL
);

SELECT * FROM petshop ORDER BY nome;